# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170522_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votes',
            name='candidate',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stud', to='polls.Student'),
        ),
        migrations.DeleteModel(
            name='Votes',
        ),
    ]
