# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20170523_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.Student'),
        ),
    ]
